;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-append
	evil-backward-char
	evil-delete
	evil-end-of-line
	evil-forward-char
	evil-insert
	evil-normal-state
	evil-visual-char
	smex
	))

(setq mc/cmds-to-run-once
      '(
	evil-delete-char
	evil-next-line
	evil-previous-line
	evil-scroll-line-down
	evil-search-next
	))
